on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: mylzacr.azurecr.io
        username: ${{ secrets.acr_mylzacr_username }}
        password: ${{ secrets.acr_mylzacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/packages/@vuepress/markdown/__tests__/fragments" -f  "packages/@vuepress/markdown/__tests__/fragments/Dockerfile" -t mylzacr.azurecr.io/gggt:${{ github.sha }} --label dockerfile-path=packages/@vuepress/markdown/__tests__/fragments/Dockerfile
        docker push mylzacr.azurecr.io/gggt:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_gggt_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep default | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace default`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: default
        container-registry-url: mylzacr.azurecr.io
        container-registry-username: ${{ secrets.acr_mylzacr_username }}
        container-registry-password: ${{ secrets.acr_mylzacr_password }}
        secret-name: gggtdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: default
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          mylzacr.azurecr.io/gggt:${{ github.sha }}
        imagepullsecrets: |
          gggtdockerauth
